### PR TITLE
Update package to v0.0.12

### PR DESCRIPTION
**Pull request by MarcSkovMadsen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` @conda-forge-admin please rerender
* [x] Ensured the license file is being packaged.

Adds PDBeMolstar widget

### CODE REVIEW

**Comment by MarcSkovMadsen** [comment]
@conda-forge-admin. How do I get SHA256 mismatch issue leading to failed pipelines solved? Thanks.

**Comment by MarcSkovMadsen** [comment]
Ahhh. I need to update the SHA256 value also. Why is it not it `set` section? That is the section I would expect to have to update.

image

**Comment by MarcSkovMadsen** [comment]
@conda-forge/core I need help here. I don't have rights to merge. I am the creator of panel-chemistry and the panel-chemistry-feedstock. Thanks

I think the cause is shown below.

image

**Comment by dopplershift** [comment]
When the feedstock was created, you *should* have received an invitation to join the organization with permissions on this repo. Let's try to send one again.

@conda-forge-admin, please update team

**Comment by dopplershift** [comment]
Trying again since GitHub webhooks were having issues earlier

@conda-forge-admin, please update team

**Comment by MarcSkovMadsen** [comment]
Hi @dopplershift . Thanks for taking a look. Where would I find the invitation? I've looked through both github notifications and my email without luck. 

Please note my github username is `MarcskovMadsen` in the yaml file. The correct one is `MarcSkovMadsen` and a part of this PR.

**Comment by dopplershift** [comment]
Since you are the original maintainer, I'll merge and see if that fixes. If that doesn't, we can open a new *issue* and see if that triggers the bot. I'm not clear if the casing of the user name actually matters.

**Comment by MarcSkovMadsen** [comment]
Thanks. I got an invitation now to the team and accepted :-)

**Comment by MarcSkovMadsen** [comment]
I checked the autogenerated pull request and there I could now merge. So I think I have the rights now.

image

**Comment by dopplershift** [comment]
I also see you now in the team that has access to the repo.

**Pull request merged**
